version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: graphql-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: graphql-db
      POSTGRES_USER: graphql
      POSTGRES_PASSWORD: graphql
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d